### ISSUE TITLE
Global rate limit for use of faucet

### ISSUE THREAD

**Issue by stephenpdiesel** [EOS-Nation/eosio.faucet#2]
We would like a global rate limit with configurable parameters. The rate limit should not be based on the current mechanism used for the per-account limit, but should instead use some sort of averaging.

**Comment by DenisCarriere** [comment]
Implemented global rate limits:

### Global parameters:
- maximum 5000 faucet events per 60 minutes

### User paramters:
- Cooldown period of 60 seconds per faucet event
- maximum 10 faucet events per 24 hours
- decrementing amount received per each event within 24 hour period:
  - 1.0 EOS
  - 0.9 EOS
  - 0.8 EOS
  - etc...

Would result in a maximum of 120,000 faucet events per 24 hour period (can always be configured to be lower or higher)
